#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cmd_common.h"

#include "../pgp/kdf.h"
#include "../pgp/keywrap.h"
#include "../pgp/seipd.h"
#include "../pgp/packet.h"

#include "../device/device.h"
#include "../device/protocol.h"
#include "../device/device_tup.h"

typedef struct 
{
    const char *input_file;
    const char *output_file; /* NULL = auto name */
    const char *port;
    int         slot;
    int         verbose;
} decrypt_args_t;

static int parse_decrypt_args(int argc, char *argv[], decrypt_args_t *args)
{
    args->input_file = NULL;
    args->output_file = NULL;
    args->port = "/dev/ttyACM0";
    args->slot = 0;
    args->verbose = 0;

    for (int i = 1; i < argc; i++) 
    {
        if (strcmp(argv[i], "--port") == 0 && i + 1 < argc) 
        {
            args->port = argv[++i];
        } 
        else if (strcmp(argv[i], "--out") == 0 && i + 1 < argc) 
        {
            args->output_file = argv[++i];
        } 
        else if (strcmp(argv[i], "--slot") == 0 && i + 1 < argc) 
        {
            args->slot = atoi(argv[++i]);
        } 
        else if (strcmp(argv[i], "--verbose") == 0 || strcmp(argv[i], "-v") == 0) 
        {
            args->verbose = 1;
        } 
        else if (argv[i][0] != '-') 
        {
            args->input_file = argv[i];
        } 
        else 
        {
            fprintf(stderr, "Unknown option: %s\n", argv[i]);
            return -1;
        }
    }

    if (!args->input_file) 
    {
        fprintf(stderr, "Usage: pico-pgp decrypt <plik.pgp> [--port /dev/ttyACM0] [--out plik]\n");
        return -1;
    }

    return 0;
}

static void make_output_path(const char *input, char *out, size_t out_size)
{
    size_t len = strlen(input);
    
    if (len > 4 && strcmp(input + len - 4, ".pgp") == 0) 
    {
        snprintf(out, out_size, "%.*s", (int)(len - 4), input);
    } 
    else 
    {
        snprintf(out, out_size, "%s.dec", input);
    }
}

void cmd_decrypt(int argc, char *argv[])
{
    decrypt_args_t args;
    if (parse_decrypt_args(argc, argv, &args) != 0) 
    {
        return;
    }

    size_t   file_len = 0;
    uint8_t *file_buf = read_file(args.input_file, &file_len);
    if (!file_buf) 
    {
        fprintf(stderr, "Error: cannot open '%s'\n", args.input_file);
        return;
    }

    uint8_t eph_pub_xy[64];
    uint8_t wrapped_sk[40];
    size_t  pkesk_consumed = 0;

    if (packet_parse_pkesk(file_buf, file_len, eph_pub_xy, wrapped_sk, &pkesk_consumed) != 0) 
    {
        fprintf(stderr, "Error: Could not parse PKESK packet\n\tCheck if the file is a valid .pgp file generated by pico-pgp\n");
        free(file_buf);
        return;
    }

    if (args.verbose) 
    {
        dump_hex("eph_pub_xy[0..7]", eph_pub_xy, 8);
        dump_hex("wrapped_sk[0..7]", wrapped_sk, 8);
        fprintf(stderr, "PKESK skonsumował: %zu B\n", pkesk_consumed);
    }

    const uint8_t *ciphertext = NULL;
    size_t ct_len = 0;
    size_t seipd_consumed = 0;

    if (packet_parse_seipd(file_buf + pkesk_consumed, file_len  - pkesk_consumed, &ciphertext, &ct_len, &seipd_consumed) != 0) 
    {
        fprintf(stderr, "Error: Could not parse SEIPD packet\n");
        free(file_buf);
        return;
    }

    if (args.verbose) 
    {
        fprintf(stderr, "SEIPD ciphertext: %zu B\n", ct_len);
    }

    int fd = device_open(args.port);
    if (fd < 0) 
    {
        fprintf(stderr, "Error: unable to open port '%s'\n\tCheck if Pico is connected.\n", args.port);
        free(file_buf);
        return;
    }

    uint8_t  recipient_pub[64];
    uint16_t pub_len = 0;

    uint8_t slot_byte = (uint8_t)args.slot;
    if (device_send_cmd(fd, CMD_GET_PUBLIC_KEY, &slot_byte, 1, NULL, recipient_pub, &pub_len) != 0 || pub_len != 64) 
    {
        fprintf(stderr, "Error: cannot read pub key from slot %d\n", args.slot);
        device_close(fd);
        free(file_buf);
        return;
    }

    uint8_t fingerprint[20];
    compute_fingerprint(recipient_pub, fingerprint);

    if (args.verbose) 
    {
        dump_hex("fingerprint", fingerprint, 20);
    }

    uint8_t ecdh_payload[65];
    ecdh_payload[0] = (uint8_t)args.slot;;
    memcpy(ecdh_payload + 1, eph_pub_xy, 64);

    uint8_t shared_secret[32];
    uint16_t ss_len = 0;

    int tup_rc = pgp_device_send_cmd_tup(fd, CMD_ECDH_REQUEST, ecdh_payload, 65, shared_secret, &ss_len);
    device_close(fd);

    if (tup_rc == -2) 
    {
        fprintf(stderr, "Error: TUP timeout - button not pressed.\n");
        free(file_buf);
        return;
    }

    if (tup_rc != 0 || ss_len != 32) 
    {
        fprintf(stderr, "Error: ECDH_REQUEST failed (rc=%d, len=%u)\n", tup_rc, ss_len);
        free(file_buf);
        return;
    }

    if (args.verbose) 
    {
        dump_hex("shared_secret[0..7]", shared_secret, 8);
    }

    uint8_t wrapping_key[32];

    if (pgp_ecdh_kdf(shared_secret, fingerprint, wrapping_key) != 0) 
    {
        fprintf(stderr, "Error: KDF\n");
        memset(shared_secret, 0, sizeof(shared_secret));
        free(file_buf);
        return;
    }

    memset(shared_secret, 0, sizeof(shared_secret));

    uint8_t session_key[32];

    int unwrap_rc = aes256_key_unwrap(wrapping_key, wrapped_sk, session_key);
    memset(wrapping_key, 0, sizeof(wrapping_key));

    if (unwrap_rc != 0) {
        fprintf(stderr, "Error: AES Key Unwrap unsuccessful\n\tPossible causes:\n\t- wrong slot (--slot N)\n\t- file encrypted with a different key\n\t- corrupted data in the PKESK packet\n");
        free(file_buf);
        return;
    }

    uint8_t *plaintext = NULL;
    size_t   pt_len    = 0;

    int dec_rc = seipd_decrypt(session_key, ciphertext, ct_len, &plaintext, &pt_len);
    memset(session_key, 0, sizeof(session_key));

    if (dec_rc == -2) 
    {
        fprintf(stderr, "Error: resync check failed - bad key or corrupted data\n");
        free(file_buf);
        return;
    } 
    else if (dec_rc == -3) 
    {
        fprintf(stderr, "Error: MDC integrity check failed - data has been modified!\n");
        free(file_buf);
        return;
    } 
    else if (dec_rc != 0) 
    {
        fprintf(stderr, "Error: SEIPD decrypt (%d)\n", dec_rc);
        free(file_buf);
        return;
    }

    free(file_buf);

    char out_path[4096];
    if (args.output_file) 
    {
        snprintf(out_path, sizeof(out_path), "%s", args.output_file);
    } 
    else 
    {
        make_output_path(args.input_file, out_path, sizeof(out_path));
    }

    if (write_file(out_path, plaintext, pt_len) != 0) 
    {
        fprintf(stderr, "Error: saving file '%s'\n", out_path);
    } 
    else 
    {
        printf("Decrypted: %s  (%zu B)\n", out_path, pt_len);
    }

    free(plaintext);
}